select * from books order by Code_book asc;
select Code_book, Title_book, Pages from books order by Title_book asc, Pages desc;
select Name_delivery, Phone, INN from deliveries order by INN desc;
select Name_delivery, INN,Phone, Address, Code_delivery from deliveries;
select Publish, City, Code_publish from publishing_house;
select Title_book, Pages, Name_author from books join authors on authors.Code_author = books.Code_author;
select Title_book, Pages, Name_delivery from books join purchases on purchases.Code_book=books.Code_book join deliveries on purchases.Code_delivery=deliveries.Code_delivery;
select Title_book, Pages, Publish, City from books join publishing_house on publishing_house.Code_publish=books.Code_publish;
select Name_company, Phone, INN from deliveries where Name_company like "ОАО%";
select Title_book, Pages, Name_author from books join authors on authors.Code_author=books.Code_author where Title_book like "Капитанская%";
select Name_author from authors where Name_author like "Толстой%";
select Publish from publishing_house where City !="Москва";
select Title_book, Publish from books join publishing_house on publishing_house.Code_publish=books.Code_publish where Publish !="Терра";
select Name_author from authors where Birthday between '1970-01-01' and '1987-06-01';
select Title_book, Amount from books join purchases on purchases.Code_book=books.Code_book where Date_order between '2003-12-23 00:00:00.000000' and '2012-12-23 00:00:00.000000';
select Title_book, Pages from books where Pages between '200'and'300';
select Name_author from authors where Name_author between 'П' and 'Т';
select Title_book, Amount from books join purchases on purchases.Code_book=books.Code_book where Code_delivery between '2' and '3';	
select Title_book from books join publishing_house on publishing_house.Code_publish=books.Code_publish where Publish in ('Правда', 'Терра');
select Title_book, Name_author from books join authors on authors.Code_author=books.Code_author where Name_author in ('Пушкин','Тургенев');
select Name_author from authors where Name_author like "Т%";
select Publish from publishing_house where Publish like "%ель%";
select Name_company from deliveries where Name_company like "%грам";
select Code_delivery, Date_order, Title_book, Amount, Cost from books join purchases on purchases.Code_book=books.Code_book where Amount>100 or Cost between '200' and '500';
select authors.Code_author, Name_author, Title_book, Code_publish, Pages from books join authors on authors.Code_author=books.Code_author where Code_publish between '1' and '2'and Pages>120;
select Publish, Title_book, City from publishing_house join books on books.Code_publish=publishing_house.Code_publish where Title_book like "Дым" and City like 'Санкт-Петербург';
select Name_company, Title_book, Date_order from books join purchases on purchases.Code_book=books.Code_book join deliveries on deliveries.Code_delivery=purchases.Code_delivery where Date_order between '2003-12-23 00:00:00.000000' and '2017-08-16 00:00:00.000000';
select Name_author, Publish from authors join books on books.Code_author=authors.Code_author join publishing_house on publishing_house.Code_publish=books.Code_publish where Publish like 'Астрель';
select Name_company, Publish from deliveries join purchases on purchases.Code_delivery=deliveries.Code_delivery join books on books.Code_book=purchases.Code_book join publishing_house on publishing_house.Code_publish=books.Code_publish where Publish like 'Терра';
select authors.Name_author, Title_book, Name_company from authors join books on books.Code_author=authors.Code_author join purchases on purchases.Code_book=books.Code_book join deliveries on deliveries.Code_delivery=purchases.Code_delivery where Name_company like 'ОАО Телеграм';
select Title_book, sum(Cost*Amount) as "Общая сумма" from purchases join books on books.Code_book=purchases.Code_book group by Title_book;
select Title_book, sum(Cost/Pages) as "cost one pages" from books join purchases on books.Code_book=purchases.Code_book group by Title_book;
select Name_author, year(curdate())-year(Birthday) as "year" from authors;
select  Cost, sum(Cost) as "Cost ont" from purchases join deliveries on purchases.Code_delivery=deliveries.Code_delivery where Name_company like 'ОАО Телеграм' group by Cost;
select count(*) AS "Col postavok" from purchases where Date_order between '2003-12-23 00:00:00.000000' and '2012-09-19 00:00:00.000000';
select avg(Cost) as "Cредняя цена", avg(Amount) as "Среднее количество", authors.Name_author from purchases join books on purchases.Code_book=books.Code_book join authors on books.Code_author=authors.Code_author where Name_author like 'Толстой' group by authors.Name_author;
select purchases.*, Books.Title_book from purchases join books on purchases.Code_book=books.Code_book where (purchases.Cost * purchases.Amount)=(select min(Cost*Amount) from purchases);
select purchases.*, Title_book from purchases join books on purchases.Code_book=books.Code_book where (purchases.Cost * purchases.Amount)=(select max(Cost*Amount) from purchases);
select Title_book, sum(Cost*Amount) as Itog from books join purchases on books.Code_book=purchases.Code_book where Date_order between '2003-12-23 00:00:00.000000' and '2012-09-19 00:00:00.000000' group by Title_book;
select Title_book, sum(Cost/Pages) as One_page from books join purchases on books.Code_book=purchases.Code_book group by Title_book;
select sum(cost) as "sum_cost", Name_company from purchases join deliveries on purchases.Code_delivery = deliveries.Code_delivery where Name_company like "ОАО Телеграм" group by Name_company;